spring:
  datasource:
    url: "jdbc:h2:mem:filmorate;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS filmorate;"
    url2: "jdbc:h2:file:./db/filmorate;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS filmorate;"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: filmorate
  flyway:
    enabled: true
    validate-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console